 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tweets", type: :request do
  describe '/tweets' do
    it '/tweets' do
        get '/tweets'
        expect(response).to have_http_status(200)
    end
  end
  describe '/tweets/:id' do
      
      context 'idがある場合' do
          let(:tweet2) {FactoryBot.create :tweet2}
      
      
          it 'リクエストが成功すること' do
              get tweet_path tweet2.id
              expect(response).to have_http_status(200)
          end
          
          it 'Titleが表示されていること' do
              get tweet_path tweet2.id
              expect(response.body).to include "aa"
          end
      
      end
      
    
  end
end
